export const FETCH_POSTS = 'FETCH_POSTS';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const CREATE_POST = 'CREATE_POST';
export const GET_POST = 'GET_POST';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const DOWNLOAD_NEW_USER_PHOTO = 'DOWNLOAD_NEW_USER_PHOTO';
export const FETCH_TRACKS = 'FETCH_TRACKS';
export const CREATE_TRACK = 'CREATE_TRACK';
export const SET_CURRENT_TRACK ='SET_CURRENT_TRACK';
export const FETCH_BANDS = 'FETCH_BANDS';

